/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import Classes.Books;
import Connection.Connections;
import Connection.TableNewColors;
import Connection.Tools;
import javax.swing.JTable;

/**
 *
 * @author mohammadzreik
 */
public class FrmBorrow extends javax.swing.JFrame {

    /** Creates new form FrmBorrow */
    public FrmBorrow() {
        initComponents();
      
    }
    Books book = new Books();
    private void SelectInfo(){
        int Row = Borrowtable.getSelectedRow();
                try {
    txtISBN.setText(Borrowtable.getValueAt(Row,0).toString() );
    txtTitle.setText(Borrowtable.getValueAt(Row, 1).toString() );
    txtAuthor.setText(Borrowtable.getValueAt(Row, 2).toString());
    txtPublisher.setText(Borrowtable.getValueAt(Row, 3).toString());
    txtShelf.setText(Borrowtable.getValueAt(Row, 4).toString());
    txtGenre.setText(Borrowtable.getValueAt(Row, 5).toString());
    txtStatus.setText(Borrowtable.getValueAt(Row, 6).toString());
    txtNumberOfBorrowing.setText(Borrowtable.getValueAt(Row, 7).toString());
                 }catch(Exception ex){
                Tools.MsgBox(ex.getMessage());
                }
    }
   
    public void GetTableInfo(String TableNameInDB, JTable table){
        Connections.FillTable(TableNameInDB, table);
    }
    
    
    
    
    
    
 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtAuthor = new Controls.JTextBox();
        txtGenre = new Controls.JTextBox();
        txtTitle = new Controls.JTextBox();
        txtISBN = new Controls.JTextBox();
        txtStatus = new Controls.JTextBox();
        txtPublisher = new Controls.JTextBox();
        txtShelf = new Controls.JTextBox();
        txtNumberOfBorrowing = new Controls.JTextBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Borrowtable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new Controls.JTextBox();
        searchbtn = new javax.swing.JLabel();
        RadTitle = new javax.swing.JRadioButton();
        RadNumberOfBorrowing = new javax.swing.JRadioButton();
        RadAuthor = new javax.swing.JRadioButton();
        RadISBN = new javax.swing.JRadioButton();
        RadShelf = new javax.swing.JRadioButton();
        RadPublisher = new javax.swing.JRadioButton();
        RadGenre = new javax.swing.JRadioButton();
        RadStatus = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1090, 559));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1090, 559));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Shelf");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 290, 40, 20);

        jLabel11.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ISBN");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 150, 40, 20);

        jLabel12.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Title");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 220, 40, 20);

        jLabel13.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Author");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 360, 50, 20);

        jLabel15.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Genre");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(200, 360, 50, 20);

        jLabel17.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Publisher");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(200, 220, 70, 20);

        jLabel19.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Status");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(200, 150, 50, 20);

        jLabel21.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("N.Borrowing");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(200, 290, 90, 20);

        txtAuthor.setEditable(false);
        getContentPane().add(txtAuthor);
        txtAuthor.setBounds(20, 390, 160, 27);

        txtGenre.setEditable(false);
        getContentPane().add(txtGenre);
        txtGenre.setBounds(200, 390, 160, 27);

        txtTitle.setEditable(false);
        getContentPane().add(txtTitle);
        txtTitle.setBounds(20, 250, 160, 27);

        txtISBN.setEditable(false);
        getContentPane().add(txtISBN);
        txtISBN.setBounds(20, 180, 160, 27);

        txtStatus.setEditable(false);
        getContentPane().add(txtStatus);
        txtStatus.setBounds(200, 180, 160, 27);

        txtPublisher.setEditable(false);
        getContentPane().add(txtPublisher);
        txtPublisher.setBounds(200, 250, 160, 27);

        txtShelf.setEditable(false);
        getContentPane().add(txtShelf);
        txtShelf.setBounds(20, 320, 160, 27);

        txtNumberOfBorrowing.setEditable(false);
        getContentPane().add(txtNumberOfBorrowing);
        txtNumberOfBorrowing.setBounds(200, 320, 160, 27);

        Borrowtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Publisher", "Shelf", "Genre", "Status", "N. Borrowing"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Borrowtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BorrowtableMouseClicked(evt);
            }
        });
        Borrowtable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BorrowtableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Borrowtable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(390, 150, 690, 406);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/testb.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 80, 90);

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Library Books");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 270, 70);
        getContentPane().add(txtSearch);
        txtSearch.setBounds(410, 110, 600, 27);

        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/searchbtn.png"))); // NOI18N
        searchbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbtnMouseClicked(evt);
            }
        });
        getContentPane().add(searchbtn);
        searchbtn.setBounds(1020, 100, 40, 40);

        RadTitle.setForeground(new java.awt.Color(255, 255, 255));
        RadTitle.setText("Title");
        RadTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RadTitle);
        RadTitle.setBounds(480, 70, 50, 18);

        RadNumberOfBorrowing.setForeground(new java.awt.Color(255, 255, 255));
        RadNumberOfBorrowing.setText("N.Borrowing");
        RadNumberOfBorrowing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RadNumberOfBorrowing);
        RadNumberOfBorrowing.setBounds(970, 70, 100, 18);

        RadAuthor.setForeground(new java.awt.Color(255, 255, 255));
        RadAuthor.setText("Author");
        RadAuthor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RadAuthor);
        RadAuthor.setBounds(550, 70, 70, 18);

        RadISBN.setBackground(new java.awt.Color(255, 255, 255));
        RadISBN.setForeground(new java.awt.Color(255, 255, 255));
        RadISBN.setText("ISBN");
        RadISBN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RadISBN);
        RadISBN.setBounds(410, 70, 50, 18);

        RadShelf.setForeground(new java.awt.Color(255, 255, 255));
        RadShelf.setText("Shelf");
        RadShelf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RadShelf);
        RadShelf.setBounds(740, 70, 50, 18);

        RadPublisher.setForeground(new java.awt.Color(255, 255, 255));
        RadPublisher.setText("Publisher");
        RadPublisher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RadPublisher);
        RadPublisher.setBounds(640, 70, 80, 18);

        RadGenre.setForeground(new java.awt.Color(255, 255, 255));
        RadGenre.setText("Genre");
        RadGenre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RadGenre);
        RadGenre.setBounds(810, 70, 70, 18);

        RadStatus.setForeground(new java.awt.Color(255, 255, 255));
        RadStatus.setText("Status");
        RadStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RadStatus);
        RadStatus.setBounds(890, 70, 60, 18);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Borrow");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(230, 490, 120, 40);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAutoscrolls(true);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 420, 160, 10);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setAutoscrolls(true);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(200, 420, 160, 10);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setAutoscrolls(true);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(20, 280, 160, 10);

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setAutoscrolls(true);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(20, 350, 160, 10);

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setAutoscrolls(true);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(20, 210, 160, 10);

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setAutoscrolls(true);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(200, 210, 160, 10);

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setAutoscrolls(true);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(200, 280, 160, 10);

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setAutoscrolls(true);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(200, 350, 160, 10);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/back32.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 510, 40, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/exit.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 510, 32, 40);

        jPanel3.setBackground(new java.awt.Color(64, 1, 64));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 380, 560);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(380, 0, 710, 560);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
        
      GetTableInfo( "books", Borrowtable);
      
       Group.add(RadISBN);
       Group.add(RadTitle);
       Group.add(RadAuthor);
       Group.add(RadPublisher);
       Group.add(RadShelf);
       Group.add(RadGenre);
       Group.add(RadStatus);
       Group.add(RadNumberOfBorrowing);
    }//GEN-LAST:event_formWindowOpened

    private void BorrowtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrowtableMouseClicked
       SelectInfo();
    }//GEN-LAST:event_BorrowtableMouseClicked

    private void BorrowtableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BorrowtableKeyReleased
         SelectInfo();
    }//GEN-LAST:event_BorrowtableKeyReleased

    private void searchbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbtnMouseClicked
        String Statement = "Select * from Books where ";
        String Statement2 = " like '%"+ txtSearch.getText()+ "%' ";
        if (RadISBN.isSelected()){
            Statement += " ISBN " + Statement2;
        }
        else if (RadTitle.isSelected()){
            Statement += " Title " + Statement2;
        }
        else if (RadShelf.isSelected()){
             Statement += " Shelf " + Statement2;
        }
        else if (RadGenre.isSelected()){
             Statement += " Genre " + Statement2;
        }
        else if (RadPublisher.isSelected()){
             Statement += " Publisher " + Statement2;
        }
         else if (RadAuthor.isSelected()){
             Statement += " Author " + Statement2;
        }
        else if (RadStatus.isSelected()){
             Statement += " Status " + Statement2;
        }
        else {
             Statement += " NumberOfBorrowing " + Statement2;
        }
        
        book.GetSomeRows(Statement, Borrowtable);
        int Row = Borrowtable.getRowCount();
        if (Row == 0){
            Tools.MsgBoxErrorX("No result!","Searsh not found");
            txtSearch.setText("");
             book.GetTableInfo("Books", Borrowtable);
            txtSearch.requestFocus();
        }
    }//GEN-LAST:event_searchbtnMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
      this.dispose();
      Tools.OpenForm(new FrmManagement());
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBorrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBorrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBorrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBorrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBorrow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Borrowtable;
    private javax.swing.ButtonGroup Group;
    private javax.swing.JRadioButton RadAuthor;
    private javax.swing.JRadioButton RadGenre;
    private javax.swing.JRadioButton RadISBN;
    private javax.swing.JRadioButton RadNumberOfBorrowing;
    private javax.swing.JRadioButton RadPublisher;
    private javax.swing.JRadioButton RadShelf;
    private javax.swing.JRadioButton RadStatus;
    private javax.swing.JRadioButton RadTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel searchbtn;
    private Controls.JTextBox txtAuthor;
    private Controls.JTextBox txtGenre;
    private Controls.JTextBox txtISBN;
    private Controls.JTextBox txtNumberOfBorrowing;
    private Controls.JTextBox txtPublisher;
    private Controls.JTextBox txtSearch;
    private Controls.JTextBox txtShelf;
    private Controls.JTextBox txtStatus;
    private Controls.JTextBox txtTitle;
    // End of variables declaration//GEN-END:variables

}
