/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.*;
import Classes.Customer;
import Connection.TableNewColors;
import Connection.Tools;
import java.awt.Cursor;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.*;
/**
 *
 * @author Death-PC
 */
public class FrmCustomerMenu extends javax.swing.JFrame {

    static String email;
    static String card;
    /**
     * Creates new form FrmCustomerMenu
     */
    public FrmCustomerMenu() {
        initComponents();
        
        
    
    }
public FrmCustomerMenu(String card, String name,String Email){
         this.card = card;
                 
         email = Email;
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        exitbtn = new javax.swing.JLabel();
        showlable = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        borrowbutton = new javax.swing.JLabel();
        historybutton = new javax.swing.JLabel();
        passwordbutton = new javax.swing.JLabel();
        infobutton = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(539, 429));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(540, 463));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setLayout(null);

        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/logout.png"))); // NOI18N
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitbtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitbtnMouseEntered(evt);
            }
        });
        jPanel3.add(exitbtn);
        exitbtn.setBounds(11, 60, 37, 47);

        showlable.setFont(new java.awt.Font("sansserif", 2, 24)); // NOI18N
        showlable.setForeground(new java.awt.Color(255, 255, 255));
        showlable.setText("Information");
        jPanel3.add(showlable);
        showlable.setBounds(119, 38, 311, 32);

        date.setFont(new java.awt.Font("sansserif", 2, 10)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date");
        jPanel3.add(date);
        date.setBounds(453, 82, 72, 25);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 350, 540, 120);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Customer Menu");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/menu.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 540, 110);

        jPanel1.setBackground(new java.awt.Color(44, 0, 44));
        jPanel1.setForeground(new java.awt.Color(44, 0, 44));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Borrow");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("History");

        borrowbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/histor.png"))); // NOI18N
        borrowbutton.setToolTipText("");
        borrowbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrowbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrowbuttonMouseExited(evt);
            }
        });

        historybutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/book.png"))); // NOI18N
        historybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historybuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historybuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historybuttonMouseExited(evt);
            }
        });

        passwordbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/book.png"))); // NOI18N
        passwordbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordbuttonMouseExited(evt);
            }
        });

        infobutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/key.png"))); // NOI18N
        infobutton.setToolTipText("");
        infobutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        infobutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infobuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infobuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infobuttonMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Change info");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Change pass");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrowbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(infobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(passwordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(borrowbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(historybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 110, 540, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        this.dispose();
        Tools.OpenForm(new Menu());
    }//GEN-LAST:event_exitbtnMouseClicked

    private void exitbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseExited
        showlable.setVisible(false);
    }//GEN-LAST:event_exitbtnMouseExited

    private void exitbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseEntered
        exitbtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        showlable.setText("            Back to menu");
        showlable.setVisible(true);
    }//GEN-LAST:event_exitbtnMouseEntered

    private void borrowbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowbuttonMouseClicked

        this.dispose();
        Tools.OpenForm(new FrmBooks_Borrow(card, Connection.Connections.GetCustomerName(email), email));
    }//GEN-LAST:event_borrowbuttonMouseClicked
// email but not name? need name
    private void borrowbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowbuttonMouseExited
        showlable.setVisible(false);
    }//GEN-LAST:event_borrowbuttonMouseExited

    private void borrowbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowbuttonMouseEntered
        borrowbutton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        showlable.setText("      Borrow Books");
        showlable.setVisible(true);
    }//GEN-LAST:event_borrowbuttonMouseEntered

    private void historybuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historybuttonMouseClicked
        this.dispose();
        Tools.OpenForm(new FrmHistoryC(card, email));
    }//GEN-LAST:event_historybuttonMouseClicked

    private void historybuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historybuttonMouseExited
        showlable.setVisible(false);
    }//GEN-LAST:event_historybuttonMouseExited

    private void historybuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historybuttonMouseEntered
        historybutton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        showlable.setText("        Check your history");
        showlable.setVisible(true);

    }//GEN-LAST:event_historybuttonMouseEntered

    private void passwordbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordbuttonMouseClicked
        // TODO add your handling code here:
           this.dispose();
        Tools.OpenForm(new FrmResetPassword());
    }//GEN-LAST:event_passwordbuttonMouseClicked

    private void passwordbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordbuttonMouseEntered
        // TODO add your handling code here:
        historybutton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        showlable.setText("        Change your password");
        showlable.setVisible(true);

        
    }//GEN-LAST:event_passwordbuttonMouseEntered

    private void passwordbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordbuttonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordbuttonMouseExited

    private void infobuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infobuttonMouseClicked
        // TODO add your handling code here:
              this.dispose();
        Tools.OpenForm(new FrmCustomer_ChangeInfo(card, email));
    }//GEN-LAST:event_infobuttonMouseClicked

    private void infobuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infobuttonMouseEntered
        // TODO add your handling code here:
        historybutton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        showlable.setText("        Change your information");
        showlable.setVisible(true);

    }//GEN-LAST:event_infobuttonMouseEntered

    private void infobuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infobuttonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_infobuttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCustomerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borrowbutton;
    private javax.swing.JLabel date;
    private javax.swing.JLabel exitbtn;
    private javax.swing.JLabel historybutton;
    private javax.swing.JLabel infobutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel passwordbutton;
    private javax.swing.JLabel showlable;
    // End of variables declaration//GEN-END:variables
}
