/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

/**
 *
 * @author mnaze
 */
import Classes.History;
import Connection.Connections;
import Connection.TableNewColors;
import Connection.Tools.*;
import Connection.Tools;
public class FrmCustomer_History extends javax.swing.JFrame {

    /**
     * Creates new form FrmCustomer_History
     */
    public FrmCustomer_History() {
        initComponents();
        tableHistory.setDefaultRenderer(Object.class, new TableNewColors());
        Tools.SetTableHeader(tableHistory);
        SetIcons();
    }
    static int Card;
    History history = new History();
    public FrmCustomer_History(int Card , String name,String Email) {
        initComponents();
        tableHistory.setDefaultRenderer(Object.class, new TableNewColors());
        lblName.setText("For Customer: "+name);
        Tools.SetTableHeader(tableHistory);
        String statement = "Select * From History "
                + "Where CardNumber = " + Card;
        Connections.FillCustomRows(statement, tableHistory);
        SetIcons();
        this.Card = Card;
    }
    
    private void SetIcons(){
        Tools.PutImageInLable("Search-icon-White.png", lblSearch, 30, 30);
        Tools.PutImageInLable("Descending_White.png", lblDescending, 30, 30);
        Tools.PutImageInLable("Ascending_White.png", lblAscending, 30, 30);
        Tools.PutImageInLable("Back_White.png", lblBack, 30, 30);
        Tools.PutImageInLable("exit.png", lblExit, 35, 35);
    }
    
    private void OrderItems(String order) {
        String Statement = "Select * from History where CardNumber= "+Card+" order by ";
        if (RadISBN.isSelected()){
            Statement += " ISBN " + order;
        }
        else if (radCardNumber.isSelected()){
            Statement += " CardNumber " + order;
            
        }
        else if (radAuthor.isSelected()){
             Statement += " Author " + order;
        }
         else if (radStatus.isSelected()){
             Statement += " Status " + order;
        }
        else if (radTitle.isSelected()){
             Statement += " Title " + order;
        }
         else if (radRentalDate.isSelected()){
             Statement += " Rental_Date " + order;
        }
        else if (radReturnDate.isSelected()){
             Statement += " Return_Date " + order;
        }
        history.GetSomeRows(Statement, tableHistory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtSearch = new Controls.JTextBox();
        jLabel6 = new javax.swing.JLabel();
        radCardNumber = new javax.swing.JRadioButton();
        RadISBN = new javax.swing.JRadioButton();
        radTitle = new javax.swing.JRadioButton();
        radAuthor = new javax.swing.JRadioButton();
        radStatus = new javax.swing.JRadioButton();
        radRentalDate = new javax.swing.JRadioButton();
        radReturnDate = new javax.swing.JRadioButton();
        lblSearch = new javax.swing.JLabel();
        lblDescending = new javax.swing.JLabel();
        lblAscending = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistory = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(814, 488));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(814, 488));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(44, 0, 44));
        jPanel1.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Big Caslon", 3, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/books-stack-from-top-view (1).png"))); // NOI18N
        jLabel5.setText("History");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(29, 25, 340, 84);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch);
        txtSearch.setBounds(110, 190, 420, 24);

        jLabel6.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Search");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 190, 49, 19);

        radCardNumber.setBackground(new java.awt.Color(44, 0, 44));
        radCardNumber.setFont(new java.awt.Font("Big Caslon", 0, 12)); // NOI18N
        radCardNumber.setForeground(new java.awt.Color(255, 255, 255));
        radCardNumber.setSelected(true);
        radCardNumber.setText("Card Number");
        jPanel1.add(radCardNumber);
        radCardNumber.setBounds(6, 138, 107, 28);

        RadISBN.setBackground(new java.awt.Color(44, 0, 44));
        RadISBN.setFont(new java.awt.Font("Big Caslon", 0, 12)); // NOI18N
        RadISBN.setForeground(new java.awt.Color(255, 255, 255));
        RadISBN.setText("ISBN");
        jPanel1.add(RadISBN);
        RadISBN.setBounds(131, 138, 60, 28);

        radTitle.setBackground(new java.awt.Color(44, 0, 44));
        radTitle.setFont(new java.awt.Font("Big Caslon", 0, 12)); // NOI18N
        radTitle.setForeground(new java.awt.Color(255, 255, 255));
        radTitle.setText("Title");
        jPanel1.add(radTitle);
        radTitle.setBounds(209, 138, 55, 28);

        radAuthor.setBackground(new java.awt.Color(44, 0, 44));
        radAuthor.setFont(new java.awt.Font("Big Caslon", 0, 12)); // NOI18N
        radAuthor.setForeground(new java.awt.Color(255, 255, 255));
        radAuthor.setText("Author");
        radAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAuthorActionPerformed(evt);
            }
        });
        jPanel1.add(radAuthor);
        radAuthor.setBounds(276, 138, 67, 28);

        radStatus.setBackground(new java.awt.Color(44, 0, 44));
        radStatus.setFont(new java.awt.Font("Big Caslon", 0, 12)); // NOI18N
        radStatus.setForeground(new java.awt.Color(255, 255, 255));
        radStatus.setText("Status");
        jPanel1.add(radStatus);
        radStatus.setBounds(355, 138, 67, 28);

        radRentalDate.setBackground(new java.awt.Color(44, 0, 44));
        radRentalDate.setFont(new java.awt.Font("Big Caslon", 0, 12)); // NOI18N
        radRentalDate.setForeground(new java.awt.Color(255, 255, 255));
        radRentalDate.setText("Rental Date");
        radRentalDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radRentalDateActionPerformed(evt);
            }
        });
        jPanel1.add(radRentalDate);
        radRentalDate.setBounds(434, 138, 97, 28);

        radReturnDate.setBackground(new java.awt.Color(44, 0, 44));
        radReturnDate.setFont(new java.awt.Font("Big Caslon", 0, 12)); // NOI18N
        radReturnDate.setForeground(new java.awt.Color(255, 255, 255));
        radReturnDate.setText("Return Date");
        jPanel1.add(radReturnDate);
        radReturnDate.setBounds(535, 138, 98, 28);

        lblSearch.setToolTipText("Search");
        lblSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSearch.setMaximumSize(new java.awt.Dimension(50, 50));
        lblSearch.setMinimumSize(new java.awt.Dimension(50, 50));
        lblSearch.setPreferredSize(new java.awt.Dimension(50, 50));
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchMouseExited(evt);
            }
        });
        jPanel1.add(lblSearch);
        lblSearch.setBounds(540, 170, 50, 50);

        lblDescending.setToolTipText("Order items Descending");
        lblDescending.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDescending.setMaximumSize(new java.awt.Dimension(50, 50));
        lblDescending.setMinimumSize(new java.awt.Dimension(50, 50));
        lblDescending.setPreferredSize(new java.awt.Dimension(50, 50));
        lblDescending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDescendingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDescendingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDescendingMouseExited(evt);
            }
        });
        jPanel1.add(lblDescending);
        lblDescending.setBounds(600, 170, 50, 50);

        lblAscending.setToolTipText("Order items Ascending ");
        lblAscending.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAscending.setMaximumSize(new java.awt.Dimension(50, 50));
        lblAscending.setMinimumSize(new java.awt.Dimension(50, 50));
        lblAscending.setPreferredSize(new java.awt.Dimension(50, 50));
        lblAscending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAscendingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAscendingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAscendingMouseExited(evt);
            }
        });
        jPanel1.add(lblAscending);
        lblAscending.setBounds(660, 170, 50, 50);

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Title");
        jPanel1.add(lblName);
        lblName.setBounds(290, 60, 500, 41);

        lblBack.setToolTipText("Back To Menu");
        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.setMaximumSize(new java.awt.Dimension(50, 50));
        lblBack.setMinimumSize(new java.awt.Dimension(50, 50));
        lblBack.setPreferredSize(new java.awt.Dimension(50, 50));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackMouseExited(evt);
            }
        });
        jPanel1.add(lblBack);
        lblBack.setBounds(80, 420, 50, 50);

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/exit.png"))); // NOI18N
        lblExit.setToolTipText("Exit the program");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.setMaximumSize(new java.awt.Dimension(50, 50));
        lblExit.setMinimumSize(new java.awt.Dimension(50, 50));
        lblExit.setPreferredSize(new java.awt.Dimension(50, 50));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel1.add(lblExit);
        lblExit.setBounds(20, 420, 50, 50);

        tableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Card Number", "ISBN", "Title", "Author", "Status", "Rental Date", "Returned Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableHistory);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 240, 660, 180);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(110, 220, 420, 10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 813, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void radAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radAuthorActionPerformed

    private void radRentalDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radRentalDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radRentalDateActionPerformed

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        String Statement = "Select * from History where CardNumber =" +Card +";";
        String Statement2 = " like '%"+ txtSearch.getText()+ "%' where CardNumber =" +Card +";";
        if (RadISBN.isSelected()){
            Statement += " ISBN " + Statement2;
        }
        else if (radCardNumber.isSelected()){
            Statement += " CardNumber " + Statement2;
        }
        else if (radTitle.isSelected()){
            Statement += " Title " + Statement2;
        }
        else if (radAuthor.isSelected()){
            Statement += " Author " + Statement2;
        }
        else if (radStatus.isSelected()){
            Statement += " Status " + Statement2;
        }
        else if (radRentalDate.isSelected()){
            Statement += " Rental_Date " + Statement2;
        }
        else if (radReturnDate.isSelected()){
            Statement += " Return_Date " + Statement2;
        }

       history.GetSomeRows(Statement, tableHistory);
        int Row = tableHistory.getRowCount();
        if (Row == 0){
            Tools.MsgBoxErrorX("No result!","Searching not found");
            txtSearch.requestFocus();
        }
    }//GEN-LAST:event_lblSearchMouseClicked
    
    private void lblSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseExited
        Tools.PutImageInLable("Search-icon-White.png", lblSearch, 30, 30);
    }//GEN-LAST:event_lblSearchMouseExited

    private void lblSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseEntered
        Tools.PutImageInLable("Search-icon-White.png", lblSearch, 45, 45);
    }//GEN-LAST:event_lblSearchMouseEntered

    private void lblDescendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescendingMouseClicked
        OrderItems("desc");
    }//GEN-LAST:event_lblDescendingMouseClicked

    private void lblDescendingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescendingMouseExited
        Tools.PutImageInLable("Descending_White.png", lblDescending, 30, 30);
    }//GEN-LAST:event_lblDescendingMouseExited

    private void lblDescendingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescendingMouseEntered
        Tools.PutImageInLable("Descending_White.png", lblDescending, 45, 45);
    }//GEN-LAST:event_lblDescendingMouseEntered

    private void lblAscendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAscendingMouseClicked
       OrderItems("asc");
    }//GEN-LAST:event_lblAscendingMouseClicked

    private void lblAscendingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAscendingMouseExited
        Tools.PutImageInLable("Ascending_White.png", lblAscending, 30, 30);
    }//GEN-LAST:event_lblAscendingMouseExited

    private void lblAscendingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAscendingMouseEntered
        Tools.PutImageInLable("Ascending_White.png", lblAscending, 45, 45);
    }//GEN-LAST:event_lblAscendingMouseEntered

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.dispose();
        Tools.OpenForm(new Menu());
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseEntered
        Tools.PutImageInLable("Back_White.png", lblBack, 45, 45);
    }//GEN-LAST:event_lblBackMouseEntered

    private void lblBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseExited
        Tools.PutImageInLable("Back_White.png", lblBack, 30, 30);
    }//GEN-LAST:event_lblBackMouseExited

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        boolean check = Tools.YesNoChooserBox("Do you want to quit?", "Exit!");
        if(check){
            System.exit(0);
        }
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        Tools.PutImageInLable("exit.png", lblExit, 50, 50);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        Tools.PutImageInLable("exit.png", lblExit, 35, 35);
    }//GEN-LAST:event_lblExitMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tableHistory.setDefaultRenderer(Object.class, new TableNewColors());
        btnGroup.add(RadISBN);
        btnGroup.add(radAuthor);
        btnGroup.add(radCardNumber);
        btnGroup.add(radRentalDate);
        btnGroup.add(radReturnDate);
        btnGroup.add(radStatus);
        btnGroup.add(radTitle);
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCustomer_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCustomer_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCustomer_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCustomer_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCustomer_History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadISBN;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAscending;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblDescending;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JRadioButton radAuthor;
    private javax.swing.JRadioButton radCardNumber;
    private javax.swing.JRadioButton radRentalDate;
    private javax.swing.JRadioButton radReturnDate;
    private javax.swing.JRadioButton radStatus;
    private javax.swing.JRadioButton radTitle;
    private javax.swing.JTable tableHistory;
    private Controls.JTextBox txtSearch;
    // End of variables declaration//GEN-END:variables
}
