/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;


import Classes.Books;
import Classes.Customer;
import Connection.TableNewColors;
import Connection.Tools;
import java.awt.Cursor;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.*;
/**
 *
 * @author Death-PC
 */

public class FrmCustomers extends javax.swing.JFrame {

    /**
     * Creates new form FrmCustomers
     */
    public FrmCustomers() {
        initComponents();
        jTable1.setDefaultRenderer(Object.class, new TableNewColors());
        SetLabels();
        Tools.ToDay(lblDate);
    }
    Customer customer = new Customer();
 
    
    
    private void PutInfo(){
        customer.setCardNumber(Integer.parseInt( txtCN.getText() ));
        customer.setName(txtName.getText());
        customer.setAddress(txtAddress.getText());
        customer.setPhoneNumber(txtPhone.getText());
        customer.setEmail(txtEmail.getText());
        }
    private void ClearInfo(){
    txtCN.setText(String.valueOf( customer.AutoNumber() ));
    txtName.setText("");
    txtAddress.setText("");
    txtPhone.setText("");
    txtEmail.setText("");
    customer.GetTableInfo(" Customer ", jTable1);
    txtName.requestFocus();
    }
        
 private void SetLabels(){
    
    Tools.PutImageInLable("add-512-white.png", addicon, 30, 30);
    Tools.PutImageInLable("pen.png", updateicon, 30, 30);
    Tools.PutImageInLable("Delete_Icon_White.png", deleteicon, 30, 30);
    Tools.PutImageInLable("Back_White.png", lblBack, 30, 30);
    Tools.PutImageInLable("Exit_Red.png", lblExit, 35, 35);
    Tools.PutImageInLable("Search-icon-White.png", searchbutton, 30, 30); //fix to search
    Tools.PutImageInLable("Ascending_White.png", ascbutton, 30, 30);
    Tools.PutImageInLable("Descending_White.png", descbutton, 30, 30);
    
   
    addicon.setCursor(new Cursor(Cursor.HAND_CURSOR));
    updateicon.setCursor(new Cursor(Cursor.HAND_CURSOR));
    deleteicon.setCursor(new Cursor(Cursor.HAND_CURSOR));
    lblBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
    lblExit.setCursor(new Cursor(Cursor.HAND_CURSOR));
  
    
    }
    
 
  private void OrderItems(String OrderBy){
     String Statement = "Select * from Customer ";
     
        if (CNbutton.isSelected()){
            Statement += "ORDER BY CardNumber " + OrderBy + ";";
        }
        else if (Namebutton.isSelected()){
           Statement += "ORDER BY Name " + OrderBy + ";";
        }
        else if (Addressbutton.isSelected()){
            Statement += "ORDER BY Address " + OrderBy + ";";
        }
        
        else if (Phonebutton.isSelected()){
            Statement += "ORDER BY Phone " + OrderBy + ";";
        }
       else if (Emailbutton.isSelected()){
            Statement += "ORDER BY Email " + OrderBy + ";";
        }
        customer.GetSomeRows(Statement, jTable1);
     }
 private void SelectInfo(){
        int Row = jTable1.getSelectedRow();
                try {
    txtCN.setText(jTable1.getValueAt(Row,0).toString() );
    txtName.setText(jTable1.getValueAt(Row, 1).toString() );
    txtAddress.setText(jTable1.getValueAt(Row, 2).toString());
    txtPhone.setText(jTable1.getValueAt(Row, 3).toString());
    txtEmail.setText(jTable1.getValueAt(Row, 4).toString());
                }
                catch(Exception ex){
                Tools.MsgBox(ex.getMessage());
                }
 }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        CNbutton = new javax.swing.JRadioButton();
        Namebutton = new javax.swing.JRadioButton();
        Addressbutton = new javax.swing.JRadioButton();
        Phonebutton = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        SearchField = new Controls.JTextBox();
        Emailbutton = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        addicon = new javax.swing.JLabel();
        deleteicon = new javax.swing.JLabel();
        updateicon = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        txtCN = new Controls.JTextBox();
        txtName = new Controls.JTextBox();
        txtAddress = new Controls.JTextBox();
        txtPhone = new Controls.JTextBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new Controls.JTextBox();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        searchbutton = new javax.swing.JLabel();
        ascbutton = new javax.swing.JLabel();
        descbutton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuFileAdd1 = new javax.swing.JMenuItem();
        MenuFileDelete1 = new javax.swing.JMenuItem();
        MenuFileUpdate1 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        MenuFilePrint1 = new javax.swing.JMenuItem();
        MenuFileBackUp1 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        MenuFileRefresh1 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        MenuFileHome1 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        MenuFileQuit1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuMoveToHome = new javax.swing.JMenuItem();
        MenuMoveCustomers = new javax.swing.JMenuItem();
        MenuMoveHistory = new javax.swing.JMenuItem();
        MenuMoveManagement = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 550));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(44, 0, 44));
        jPanel2.setLayout(null);

        CNbutton.setBackground(new java.awt.Color(44, 0, 44));
        buttonGroup1.add(CNbutton);
        CNbutton.setForeground(new java.awt.Color(255, 255, 255));
        CNbutton.setSelected(true);
        CNbutton.setText("Card Number");
        CNbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(CNbutton);
        CNbutton.setBounds(46, 9, 105, 25);

        Namebutton.setBackground(new java.awt.Color(44, 0, 44));
        buttonGroup1.add(Namebutton);
        Namebutton.setForeground(new java.awt.Color(255, 255, 255));
        Namebutton.setText("Name");
        Namebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(Namebutton);
        Namebutton.setBounds(172, 9, 61, 25);

        Addressbutton.setBackground(new java.awt.Color(44, 0, 44));
        buttonGroup1.add(Addressbutton);
        Addressbutton.setForeground(new java.awt.Color(255, 255, 255));
        Addressbutton.setText("Address");
        Addressbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(Addressbutton);
        Addressbutton.setBounds(254, 9, 75, 25);

        Phonebutton.setBackground(new java.awt.Color(44, 0, 44));
        buttonGroup1.add(Phonebutton);
        Phonebutton.setForeground(new java.awt.Color(255, 255, 255));
        Phonebutton.setText("Phone");
        Phonebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(Phonebutton);
        Phonebutton.setBounds(340, 10, 63, 25);

        jLabel11.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Search");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(18, 55, 59, 17);

        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });
        jPanel2.add(SearchField);
        SearchField.setBounds(82, 52, 410, 22);

        Emailbutton.setBackground(new java.awt.Color(44, 0, 44));
        buttonGroup1.add(Emailbutton);
        Emailbutton.setForeground(new java.awt.Color(255, 255, 255));
        Emailbutton.setText("Email");
        Emailbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(Emailbutton);
        Emailbutton.setBounds(420, 10, 59, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(320, 100, 500, 80);

        jPanel3.setBackground(new java.awt.Color(66, 0, 66));
        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Garamond", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 0, 33, 17);

        lblDate.setFont(new java.awt.Font("Garamond", 3, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblDate);
        lblDate.setBounds(50, 0, 97, 17);

        addicon.setToolTipText("Add Customer");
        addicon.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        addicon.setMaximumSize(new java.awt.Dimension(50, 50));
        addicon.setMinimumSize(new java.awt.Dimension(50, 50));
        addicon.setPreferredSize(new java.awt.Dimension(50, 50));
        addicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addiconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addiconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addiconMouseExited(evt);
            }
        });
        jPanel3.add(addicon);
        addicon.setBounds(130, 390, 50, 50);

        deleteicon.setToolTipText("Delete a Customer");
        deleteicon.setMaximumSize(new java.awt.Dimension(50, 50));
        deleteicon.setMinimumSize(new java.awt.Dimension(50, 50));
        deleteicon.setPreferredSize(new java.awt.Dimension(50, 50));
        deleteicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteiconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteiconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteiconMouseExited(evt);
            }
        });
        jPanel3.add(deleteicon);
        deleteicon.setBounds(190, 390, 50, 50);

        updateicon.setToolTipText("Edit a Customer");
        updateicon.setMaximumSize(new java.awt.Dimension(50, 50));
        updateicon.setMinimumSize(new java.awt.Dimension(50, 50));
        updateicon.setPreferredSize(new java.awt.Dimension(50, 50));
        updateicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateiconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateiconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateiconMouseExited(evt);
            }
        });
        jPanel3.add(updateicon);
        updateicon.setBounds(250, 390, 50, 50);

        lblExit.setToolTipText("Exit the program");
        lblExit.setMaximumSize(new java.awt.Dimension(50, 50));
        lblExit.setMinimumSize(new java.awt.Dimension(50, 50));
        lblExit.setPreferredSize(new java.awt.Dimension(50, 50));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel3.add(lblExit);
        lblExit.setBounds(20, 450, 50, 50);

        lblBack.setToolTipText("Back To Menu");
        lblBack.setMaximumSize(new java.awt.Dimension(50, 50));
        lblBack.setMinimumSize(new java.awt.Dimension(50, 50));
        lblBack.setPreferredSize(new java.awt.Dimension(50, 50));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackMouseExited(evt);
            }
        });
        jPanel3.add(lblBack);
        lblBack.setBounds(80, 450, 50, 50);

        txtCN.setEditable(false);
        txtCN.setPreferredSize(new java.awt.Dimension(60, 20));
        txtCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNActionPerformed(evt);
            }
        });
        jPanel3.add(txtCN);
        txtCN.setBounds(150, 50, 136, 27);

        txtName.setPreferredSize(new java.awt.Dimension(60, 20));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtName);
        txtName.setBounds(150, 120, 136, 27);

        txtAddress.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel3.add(txtAddress);
        txtAddress.setBounds(150, 190, 136, 27);

        txtPhone.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel3.add(txtPhone);
        txtPhone.setBounds(150, 260, 136, 27);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Card Number");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 60, 100, 16);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 130, 60, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 200, 70, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 270, 60, 16);

        jSeparator1.setMinimumSize(new java.awt.Dimension(100, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(150, 80, 137, 10);

        jSeparator2.setMinimumSize(new java.awt.Dimension(100, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(150, 150, 137, 10);

        jSeparator3.setMinimumSize(new java.awt.Dimension(100, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(150, 220, 137, 10);

        jSeparator4.setMinimumSize(new java.awt.Dimension(100, 10));
        jSeparator4.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(150, 290, 137, 10);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 340, 60, 16);

        txtEmail.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel3.add(txtEmail);
        txtEmail.setBounds(150, 330, 136, 27);

        jSeparator9.setMinimumSize(new java.awt.Dimension(100, 10));
        jSeparator9.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel3.add(jSeparator9);
        jSeparator9.setBounds(150, 360, 137, 10);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 320, 510);

        jPanel4.setBackground(new java.awt.Color(44, 0, 44));
        jPanel4.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel4.setPreferredSize(new java.awt.Dimension(700, 700));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 3, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/customers.png"))); // NOI18N
        jLabel5.setText("CUSTOMERS");

        searchbutton.setToolTipText("Search");
        searchbutton.setMaximumSize(new java.awt.Dimension(50, 50));
        searchbutton.setMinimumSize(new java.awt.Dimension(50, 50));
        searchbutton.setPreferredSize(new java.awt.Dimension(50, 50));
        searchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchbuttonMouseExited(evt);
            }
        });

        ascbutton.setToolTipText("Order items Ascending ");
        ascbutton.setMaximumSize(new java.awt.Dimension(50, 50));
        ascbutton.setMinimumSize(new java.awt.Dimension(50, 50));
        ascbutton.setPreferredSize(new java.awt.Dimension(50, 50));
        ascbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ascbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ascbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ascbuttonMouseExited(evt);
            }
        });

        descbutton.setToolTipText("Order items Descending");
        descbutton.setMaximumSize(new java.awt.Dimension(50, 50));
        descbutton.setMinimumSize(new java.awt.Dimension(50, 50));
        descbutton.setPreferredSize(new java.awt.Dimension(50, 50));
        descbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                descbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                descbuttonMouseExited(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Card Number", "Name", "Address", "Phone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ascbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ascbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 227, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(320, 0, 720, 510);

        jMenuBar1.setBackground(new java.awt.Color(44, 0, 44));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(66, 0, 66));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Options");

        MenuFileAdd1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuFileAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/plus-black-symbol (2).png"))); // NOI18N
        MenuFileAdd1.setText("Add");
        MenuFileAdd1.setToolTipText("Add new Book");
        MenuFileAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileAdd1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFileAdd1);

        MenuFileDelete1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuFileDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/Menu_Delete_Black.png"))); // NOI18N
        MenuFileDelete1.setText("Delete");
        MenuFileDelete1.setToolTipText("Delete selected Book");
        MenuFileDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileDelete1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFileDelete1);

        MenuFileUpdate1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuFileUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/Menu_Update_Black.png"))); // NOI18N
        MenuFileUpdate1.setText("Update");
        MenuFileUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileUpdate1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFileUpdate1);
        jMenu1.add(jSeparator5);

        MenuFilePrint1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuFilePrint1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/Menu_Print_Black.png"))); // NOI18N
        MenuFilePrint1.setText("Print");
        jMenu1.add(MenuFilePrint1);

        MenuFileBackUp1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuFileBackUp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/BackUp.png"))); // NOI18N
        MenuFileBackUp1.setText("Back Up");
        MenuFileBackUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileBackUp1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFileBackUp1);
        jMenu1.add(jSeparator6);

        MenuFileRefresh1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        MenuFileRefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/Menu_Refresh_Black.png"))); // NOI18N
        MenuFileRefresh1.setText("Refresh");
        MenuFileRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileRefresh1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFileRefresh1);
        jMenu1.add(jSeparator7);

        MenuFileHome1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuFileHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/Menu_Home_Black.png"))); // NOI18N
        MenuFileHome1.setText("Menu");
        MenuFileHome1.setToolTipText("Go back to Menu");
        MenuFileHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileHome1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFileHome1);
        jMenu1.add(jSeparator8);

        MenuFileQuit1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuFileQuit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/Menu_Quit_Red.png"))); // NOI18N
        MenuFileQuit1.setText("Quit");
        MenuFileQuit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileQuit1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFileQuit1);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Shortcuts");

        MenuMoveToHome.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuMoveToHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/Menu_Home_Black.png"))); // NOI18N
        MenuMoveToHome.setText("Menu");
        MenuMoveToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMoveToHomeActionPerformed(evt);
            }
        });
        jMenu2.add(MenuMoveToHome);

        MenuMoveCustomers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuMoveCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/Menu_Customers_Black.png"))); // NOI18N
        MenuMoveCustomers.setText("Customers");
        MenuMoveCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMoveCustomersActionPerformed(evt);
            }
        });
        jMenu2.add(MenuMoveCustomers);

        MenuMoveHistory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuMoveHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/Menu_History_Black.png"))); // NOI18N
        MenuMoveHistory.setText("History");
        MenuMoveHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMoveHistoryActionPerformed(evt);
            }
        });
        jMenu2.add(MenuMoveHistory);

        MenuMoveManagement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuMoveManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connection/Icons/Menu_Management_Black.png"))); // NOI18N
        MenuMoveManagement.setText("Management");
        MenuMoveManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMoveManagementActionPerformed(evt);
            }
        });
        jMenu2.add(MenuMoveManagement);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private boolean NoEmptyTextField(){
    if (txtCN.getText().equals("") || txtName.getText().equals("") || txtAddress.getText().equals("") 
            || txtPhone.getText().equals("") || txtEmail.getText().equals("") ){
        return true;
    }
    return false;
    }
    
    private void txtCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      ClearInfo();
      
    }//GEN-LAST:event_formWindowOpened

    private void addiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addiconMouseClicked
        if(!NoEmptyTextField()){ 
        PutInfo();
        customer.Add();
        ClearInfo();
        }
        else {
            Tools.MsgBoxError1("Please fill all fields", "Empty Field error");
        }    
    }//GEN-LAST:event_addiconMouseClicked

    private void addiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addiconMouseEntered
        Tools.PutImageInLable("add-512-white.png", addicon, 45, 45);
    }//GEN-LAST:event_addiconMouseEntered

    private void addiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addiconMouseExited
        Tools.PutImageInLable("add-512-white.png", addicon, 30, 30);
    }//GEN-LAST:event_addiconMouseExited

    private void deleteiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteiconMouseClicked
       if (!txtCN.getText().equals("")) {
        customer.setCardNumber(Integer.parseInt( txtCN.getText() ));
        customer.Delete();
        ClearInfo();
       }
        else {
       Tools.MsgBoxError1("Please provide Card Number of the customer you wish to delete", "Missing Card Number");
       }
    }//GEN-LAST:event_deleteiconMouseClicked

    private void deleteiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteiconMouseEntered
        Tools.PutImageInLable("Delete_Icon_White.png", deleteicon, 45, 45);
    }//GEN-LAST:event_deleteiconMouseEntered

    private void deleteiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteiconMouseExited
        Tools.PutImageInLable("Delete_Icon_White.png", deleteicon, 30, 30);
    }//GEN-LAST:event_deleteiconMouseExited

    private void updateiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateiconMouseClicked
       if (!NoEmptyTextField() ) {
       PutInfo();
       customer.Update();
       ClearInfo();
       }
       else {
            Tools.MsgBoxError1("Please fill all fields", "Empty Field error");
        }    
    }//GEN-LAST:event_updateiconMouseClicked

    private void updateiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateiconMouseEntered
        Tools.PutImageInLable("pen.png", updateicon, 45, 45);
    }//GEN-LAST:event_updateiconMouseEntered

    private void updateiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateiconMouseExited
        Tools.PutImageInLable("pen.png", updateicon, 30, 30);
    }//GEN-LAST:event_updateiconMouseExited

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        boolean check = Tools.YesNoChooserBox("Do you want to quit?", "Exit!");
        if(check){
            System.exit(0);
        }
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        Tools.PutImageInLable("Exit_Red.png", lblExit, 50, 50);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        Tools.PutImageInLable("Exit_Red.png", lblExit, 35, 35);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.dispose();
        Tools.OpenForm(new Menu());
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseEntered
        Tools.PutImageInLable("Back_White.png", lblBack, 45, 45);
    }//GEN-LAST:event_lblBackMouseEntered

    private void lblBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseExited
        Tools.PutImageInLable("Back_White.png", lblBack, 30, 30);
    }//GEN-LAST:event_lblBackMouseExited

    private void NamebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamebuttonActionPerformed

    private void AddressbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressbuttonActionPerformed

    private void CNbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNbuttonActionPerformed

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_SearchFieldActionPerformed

    
    
    
    private void searchbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseClicked
        
        String Statement = "Select * from customer where ";
        String Statement2 = " like '%"+ SearchField.getText()+ "%' ";
 
        if (CNbutton.isSelected()){
            Statement += "CardNumber " + Statement2;       
        }
        
        else if (Addressbutton.isSelected()){
           Statement += "Address " + Statement2;
        }
        
        else if (Namebutton.isSelected()){
             Statement += "Name " + Statement2;
        }
        
        else if (Phonebutton.isSelected()){
             Statement += "Phone " + Statement2;
        }
        else if (Emailbutton.isSelected()){
             Statement += "Email " + Statement2;
        }
        customer.GetSomeRows(Statement, jTable1);
        int Row = jTable1.getRowCount();
        if (Row == 0){
            Tools.MsgBoxErrorX("No result!","Search not found");
            ClearInfo();
          
        }
        
    
    }//GEN-LAST:event_searchbuttonMouseClicked

    private void searchbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseEntered
        Tools.PutImageInLable("Search-icon-White.png", searchbutton, 45, 45);
    }//GEN-LAST:event_searchbuttonMouseEntered

    private void searchbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseExited
        Tools.PutImageInLable("Search-icon-White.png", searchbutton, 30, 30);
    }//GEN-LAST:event_searchbuttonMouseExited

    private void ascbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ascbuttonMouseClicked
        OrderItems("ASC");
    }//GEN-LAST:event_ascbuttonMouseClicked

    private void ascbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ascbuttonMouseEntered
        Tools.PutImageInLable("Ascending_White.png", ascbutton, 45, 45);
    }//GEN-LAST:event_ascbuttonMouseEntered

    private void ascbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ascbuttonMouseExited
        Tools.PutImageInLable("Ascending_White.png", ascbutton, 30, 30);
    }//GEN-LAST:event_ascbuttonMouseExited

    private void descbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descbuttonMouseClicked
        OrderItems("DESC");
    }//GEN-LAST:event_descbuttonMouseClicked

    private void descbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descbuttonMouseEntered
        Tools.PutImageInLable("Descending_White.png", descbutton, 45, 45);
    }//GEN-LAST:event_descbuttonMouseEntered

    private void descbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descbuttonMouseExited
        Tools.PutImageInLable("Descending_White.png", descbutton, 30, 30);
    }//GEN-LAST:event_descbuttonMouseExited

    private void PhonebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonebuttonActionPerformed

    private void MenuFileAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileAdd1ActionPerformed
     if(!NoEmptyTextField()){ 
        PutInfo();
        customer.Add();
        ClearInfo();
        }
        else {
            Tools.MsgBoxError1("Please fill all fields", "Empty Field error");
        }    
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuFileAdd1ActionPerformed

    private void MenuFileDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileDelete1ActionPerformed
        // TODO add your handling code here:
         if (!txtCN.getText().equals("")) {
        customer.setCardNumber(Integer.parseInt( txtCN.getText() ));
        customer.Delete();
        ClearInfo();
       }
        else {
       Tools.MsgBoxError1("Please provide Card Number of the customer you wish to delete", "Missing Card Number");
       }
    }//GEN-LAST:event_MenuFileDelete1ActionPerformed

    private void MenuFileUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileUpdate1ActionPerformed
        // TODO add your handling code here:
          if (!NoEmptyTextField() ) {
       customer.Update();
       ClearInfo();
       }
       else {
            Tools.MsgBoxError1("Please fill all fields", "Empty Field error");
        }    
    }//GEN-LAST:event_MenuFileUpdate1ActionPerformed

    private void MenuFileBackUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileBackUp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuFileBackUp1ActionPerformed

    private void MenuFileRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileRefresh1ActionPerformed
        // TODO add your handling code here:
        ClearInfo();
    }//GEN-LAST:event_MenuFileRefresh1ActionPerformed

    private void MenuFileHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileHome1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.OpenForm(new Menu());
    }//GEN-LAST:event_MenuFileHome1ActionPerformed

    private void MenuFileQuit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileQuit1ActionPerformed
    boolean check = Tools.YesNoChooserBox("Do you want to quit?", "Exit!"); //change to yes/no rather than yes-no-cancel
       if(check){
        System.exit(0);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuFileQuit1ActionPerformed

    private void MenuMoveToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMoveToHomeActionPerformed
        // TODO add your handling code here:
          this.dispose();
        Tools.OpenForm(new Menu());
    }//GEN-LAST:event_MenuMoveToHomeActionPerformed

    private void MenuMoveManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMoveManagementActionPerformed
        // TODO add your handling code here:
            this.dispose();
        Tools.OpenForm(new FrmManagement());
    }//GEN-LAST:event_MenuMoveManagementActionPerformed

    private void MenuMoveHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMoveHistoryActionPerformed
        // TODO add your handling code here:
           this.dispose();  
        Tools.OpenForm(new FrmHistory());
    }//GEN-LAST:event_MenuMoveHistoryActionPerformed

    private void MenuMoveCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMoveCustomersActionPerformed
    this.dispose();  
        Tools.OpenForm(new FrmCustomers());
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuMoveCustomersActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        SelectInfo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        SelectInfo();

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void EmailbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailbuttonActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCustomers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Addressbutton;
    private javax.swing.JRadioButton CNbutton;
    private javax.swing.JRadioButton Emailbutton;
    private javax.swing.JMenuItem MenuFileAdd1;
    private javax.swing.JMenuItem MenuFileBackUp1;
    private javax.swing.JMenuItem MenuFileDelete1;
    private javax.swing.JMenuItem MenuFileHome1;
    private javax.swing.JMenuItem MenuFilePrint1;
    private javax.swing.JMenuItem MenuFileQuit1;
    private javax.swing.JMenuItem MenuFileRefresh1;
    private javax.swing.JMenuItem MenuFileUpdate1;
    private javax.swing.JMenuItem MenuMoveCustomers;
    private javax.swing.JMenuItem MenuMoveHistory;
    private javax.swing.JMenuItem MenuMoveManagement;
    private javax.swing.JMenuItem MenuMoveToHome;
    private javax.swing.JRadioButton Namebutton;
    private javax.swing.JRadioButton Phonebutton;
    private Controls.JTextBox SearchField;
    private javax.swing.JLabel addicon;
    private javax.swing.JLabel ascbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel deleteicon;
    private javax.swing.JLabel descbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel searchbutton;
    private Controls.JTextBox txtAddress;
    private Controls.JTextBox txtCN;
    private Controls.JTextBox txtEmail;
    private Controls.JTextBox txtName;
    private Controls.JTextBox txtPhone;
    private javax.swing.JLabel updateicon;
    // End of variables declaration//GEN-END:variables
}
