/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Connection.Tools;

/**
 *
 * @author mohammadzreik
 */
public class FrmRegAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegAdmin
     */
    public FrmRegAdmin() {
        initComponents();
         Tools.PutImageInLable("blue-sky.jpg", img, 351, 399);
    }

    private void registerAdmin(){
    
       
        try {
   
            String regist = "INSERT INTO loginl VALUES (" + "'" + txtuser.getText()+ "'" + "," + "'" + txtpass.getText() + "'" + ") ;" ; 
        if(txtpass.getText().equalsIgnoreCase(txtrepass.getText())){
        boolean check = Connection.Connections.RunNonQueryAdmin(regist);
        if(check) {
            Connection.Tools.MsgBoxInfo("Admin Has Been Aded", "Register");
            this.dispose();
           // Tools.OpenForm(new FrmLogin());
        }
    }
        else{
        Connection.Tools.MsgBoxInfo("Please Enter The Same Password", "Register");
       // Connection.Tools.OpenForm(new FrmRegAdmin());
      
        txtpass.setText("");
        txtrepass.setText("");
        
        txtpass.requestFocus();
        
        
        }
            
        } catch (Exception e ) {
            Connection.Tools.MsgBox(e.getMessage());
            
        }
         
        
    
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backbtn = new javax.swing.JButton();
        regbtn = new javax.swing.JButton();
        txtuser = new Controls.JTextBox();
        txtrepass = new Controls.JPasswordBox();
        txtpass = new Controls.JPasswordBox();
        txtphone = new Controls.JTextBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn);
        backbtn.setBounds(10, 360, 80, 32);

        regbtn.setText("Register");
        regbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtnActionPerformed(evt);
            }
        });
        jPanel1.add(regbtn);
        regbtn.setBounds(100, 360, 140, 32);
        jPanel1.add(txtuser);
        txtuser.setBounds(150, 110, 180, 24);
        jPanel1.add(txtrepass);
        txtrepass.setBounds(150, 190, 180, 22);
        jPanel1.add(txtpass);
        txtpass.setBounds(150, 150, 180, 22);
        jPanel1.add(txtphone);
        txtphone.setBounds(150, 230, 180, 24);

        jLabel6.setText("Phone Number :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 230, 110, 30);

        jLabel5.setText("Re-Password :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 180, 110, 40);

        jLabel4.setText("Password : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 140, 90, 50);

        jLabel3.setText("Username :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 100, 90, 40);

        jLabel2.setFont(new java.awt.Font("Apple Braille", 3, 24)); // NOI18N
        jLabel2.setText("Register Form");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 20, 210, 50);
        jPanel1.add(img);
        img.setBounds(0, 0, 350, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtnActionPerformed
        registerAdmin();
     
      
   
    }//GEN-LAST:event_regbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        this.dispose();
       // Connection.Tools.OpenForm(new FrmLogin());
    }//GEN-LAST:event_backbtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regbtn;
    private Controls.JPasswordBox txtpass;
    private Controls.JTextBox txtphone;
    private Controls.JPasswordBox txtrepass;
    private Controls.JTextBox txtuser;
    // End of variables declaration//GEN-END:variables
}
