/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.History;
import Classes.Return;
import Connection.Tools;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author Ranim
 */
public class FrmReturn extends javax.swing.JFrame {

    /**
     * Creates new form FrmReturn
     */
    public FrmReturn() {
        initComponents();
        Tools.ToDay(date);
        Tools.PutImageInLable("ReturnWh.png", lblpic, 170, 170);
          Tools.PutImageInLable("backW.png", lblback, 50, 50);
           Tools.PutImageInLable("exitW.png", lblexit, 50, 50);
            Tools.PutImageInLable("Ascending_White.png", asc, 30, 30);
             Tools.PutImageInLable("Descending_White.png", desc, 30, 30);
              Tools.PutImageInLable("Search-icon-White.png", lblSearch, 25, 25);
    }
    public FrmReturn(String card, String name){
        initComponents();
        Tools.ToDay(date);
        Tools.PutImageInLable("ReturnWh.png", lblpic, 170, 170);
          Tools.PutImageInLable("backW.png", lblback, 50, 50);
           Tools.PutImageInLable("exitW.png", lblexit, 50, 50);
            Tools.PutImageInLable("Ascending_White.png", asc, 30, 30);
            Tools.PutImageInLable("Descending_White.png", desc, 30, 30);
               Tools.PutImageInLable("Search-icon-White.png", lblSearch, 25, 25);
         txtCardNum.setText(card);
         txtName.setText(name);
        String Statement = " Select * from History where CardNumber ="+card +";";
        Connection.Connections.FillCustomRows(Statement, tableHistory);
        
    }
History history =new History();
Return retur = new Return();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupbtn = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        lblpic = new javax.swing.JLabel();
        lblback = new javax.swing.JLabel();
        lblexit = new javax.swing.JLabel();
        btnReturn = new Controls.JMyButtonPurp();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistory = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFee = new javax.swing.JLabel();
        txtCardNum = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        asc = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        txtSearch = new Controls.JTextBox();
        lblSearch = new javax.swing.JLabel();
        radISBN = new javax.swing.JRadioButton();
        radTitle = new javax.swing.JRadioButton();
        radStatus = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(102, 0, 102));

        lblpic.setBackground(new java.awt.Color(102, 0, 102));

        lblback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbackMouseExited(evt);
            }
        });

        lblexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblexitMouseExited(evt);
            }
        });

        btnReturn.setText("Return Book");
        btnReturn.setActionCommand("Return Book");
        btnReturn.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblback, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpic, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblpic, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblback, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblexit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel2.setBackground(new java.awt.Color(64, 1, 64));
        panel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Return");

        tableHistory.setForeground(new java.awt.Color(255, 255, 255));
        tableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CardNumber", "ISBN", "Title", "Author", "Status", "Rental Date", "Return Date"
            }
        ));
        tableHistory.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tableHistory);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Card Number:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fee:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name:");

        txtFee.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtFee.setForeground(new java.awt.Color(255, 255, 255));
        txtFee.setText("___________________");

        txtCardNum.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtCardNum.setForeground(new java.awt.Color(255, 255, 255));
        txtCardNum.setText("___________________");

        txtName.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setText("___________________");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SEK.");

        date.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date");

        asc.setToolTipText("Order items Ascending ");
        asc.setMaximumSize(new java.awt.Dimension(50, 50));
        asc.setMinimumSize(new java.awt.Dimension(50, 50));
        asc.setPreferredSize(new java.awt.Dimension(50, 50));
        asc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ascMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ascMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ascMouseExited(evt);
            }
        });

        desc.setToolTipText("Order items Descending");
        desc.setMaximumSize(new java.awt.Dimension(50, 50));
        desc.setMinimumSize(new java.awt.Dimension(50, 50));
        desc.setPreferredSize(new java.awt.Dimension(50, 50));
        desc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                descMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                descMouseExited(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        lblSearch.setToolTipText("Search");
        lblSearch.setMaximumSize(new java.awt.Dimension(50, 50));
        lblSearch.setMinimumSize(new java.awt.Dimension(50, 50));
        lblSearch.setPreferredSize(new java.awt.Dimension(50, 50));
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchMouseExited(evt);
            }
        });

        radISBN.setBackground(new java.awt.Color(64, 1, 64));
        radISBN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        radISBN.setForeground(new java.awt.Color(255, 255, 255));
        radISBN.setSelected(true);
        radISBN.setText("ISBN");

        radTitle.setBackground(new java.awt.Color(64, 1, 64));
        radTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        radTitle.setForeground(new java.awt.Color(255, 255, 255));
        radTitle.setText("Title");

        radStatus.setBackground(new java.awt.Color(64, 1, 64));
        radStatus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        radStatus.setForeground(new java.awt.Color(255, 255, 255));
        radStatus.setText("Status");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(113, 113, 113)
                                .addComponent(txtName))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(txtCardNum)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(radISBN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radStatus)
                                .addGap(126, 126, 126))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(jSeparator3))
                                .addGap(39, 39, 39))))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(144, 144, 144)
                        .addComponent(txtFee)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(asc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(0, 108, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radISBN)
                                    .addComponent(radTitle)
                                    .addComponent(radStatus))
                                .addGap(18, 18, 18)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtCardNum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFee)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(asc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      tableHistory.getTableHeader().setBackground(new Color (102,00,102));
        tableHistory.getTableHeader().setForeground(Color.white);
     tableHistory.getTableHeader().setReorderingAllowed(false); 
     tableHistory.getTableHeader().setResizingAllowed(false); 
     
     groupbtn.add(radISBN);
     groupbtn.add(radTitle);
     groupbtn.add(radStatus);
     
     
      lblexit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
          lblback.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
          asc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
          desc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
          lblSearch.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
          
          int Row = tableHistory.getSelectedRow();
        int fee =  Tools.CalculateDays(tableHistory.getValueAt(Row, 5).toString(), Tools.ToDay());
        txtFee.setText(String.valueOf(fee));
         
    }//GEN-LAST:event_formWindowOpened

    private void lblbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseClicked
        this.dispose();
        Connection.Tools.OpenForm(new FrmManagement());

    }//GEN-LAST:event_lblbackMouseClicked

    private void lblbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseEntered
        Tools.PutImageInLable("backW.png", lblback, 60, 60);
    }//GEN-LAST:event_lblbackMouseEntered

    private void lblbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseExited
        Tools.PutImageInLable("backW.png", lblback, 50, 50);
    }//GEN-LAST:event_lblbackMouseExited

    private void lblexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseClicked

        int choice = JOptionPane.showOptionDialog(null,
            "Are you sure you want to quit?",
            "Quit",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null, null, null);

        if (choice == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_lblexitMouseClicked

    private void lblexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseEntered
        Tools.PutImageInLable("exitW.png", lblexit, 60, 60);
    }//GEN-LAST:event_lblexitMouseEntered

    private void lblexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseExited
        Tools.PutImageInLable("exitW.png", lblexit, 50, 50);
    }//GEN-LAST:event_lblexitMouseExited

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        retur.UpdateStatusAvailable();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    
    private void OrderItems(String OrderBy){
     String Statement = "Select * from Books order by ";
        if (radISBN.isSelected()){
            Statement += " ISBN " + OrderBy;
        }
        else if (radTitle.isSelected()){
            Statement += " Title " + OrderBy;
            
        }
        
        else if (radStatus.isSelected()){
             Statement += " Status " + OrderBy;
        }
        else {
             Statement += " ISBN " + OrderBy;
        }
        history.GetSomeRows(Statement, tableHistory);
    }
    
    private void ascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ascMouseClicked
        OrderItems("asc");
    }//GEN-LAST:event_ascMouseClicked

    private void ascMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ascMouseEntered
        Tools.PutImageInLable("Ascending_White.png", asc, 45, 45);
    }//GEN-LAST:event_ascMouseEntered

    private void ascMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ascMouseExited
        Tools.PutImageInLable("Ascending_White.png", asc, 30, 30);
    }//GEN-LAST:event_ascMouseExited

    private void descMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descMouseClicked
        OrderItems("desc");
    }//GEN-LAST:event_descMouseClicked

    private void descMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descMouseEntered
        Tools.PutImageInLable("Descending_White.png", desc, 45, 45);
    }//GEN-LAST:event_descMouseEntered

    private void descMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descMouseExited
        Tools.PutImageInLable("Descending_White.png", desc, 30, 30);
    }//GEN-LAST:event_descMouseExited

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        String Statement = "Select * from Books where ";
        String Statement2 = " like '%"+ txtSearch.getText()+ "%' ";
        if (radISBN.isSelected()){
            Statement += " ISBN " + Statement2;
        }
        else if (radTitle.isSelected()){
            Statement += " Title " + Statement2;
        }
        else if (radStatus.isSelected()){
            Statement += " Status " + Statement2;
        }
        else {
            Statement += " ISBN " + Statement2;
        }

        history.GetSomeRows(Statement, tableHistory);
        int Row = tableHistory.getRowCount();
        if (Row == 0){
            Tools.MsgBoxErrorX("No result","no results were found");
           txtSearch.setText("");
            txtSearch.requestFocus();
        }
    }//GEN-LAST:event_lblSearchMouseClicked

    private void lblSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseEntered
        Tools.PutImageInLable("Search-icon-White.png", lblSearch, 30, 30);
    }//GEN-LAST:event_lblSearchMouseEntered

    private void lblSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseExited
        Tools.PutImageInLable("Search-icon-White.png", lblSearch, 25, 25);
    }//GEN-LAST:event_lblSearchMouseExited
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asc;
    private Controls.JMyButtonPurp btnReturn;
    private javax.swing.JLabel date;
    private javax.swing.JLabel desc;
    private javax.swing.ButtonGroup groupbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAscending;
    private javax.swing.JLabel lblAscending1;
    private javax.swing.JLabel lblAscending2;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lblexit;
    private javax.swing.JLabel lblpic;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JRadioButton radISBN;
    private javax.swing.JRadioButton radStatus;
    private javax.swing.JRadioButton radTitle;
    private javax.swing.JTable tableHistory;
    private javax.swing.JLabel txtCardNum;
    private javax.swing.JLabel txtFee;
    private javax.swing.JLabel txtName;
    private Controls.JTextBox txtSearch;
    // End of variables declaration//GEN-END:variables
}
